version: '3'
services:
  nginx-server:
    image: nginx:latest
    container_name: stepik.web-tech1
    volumes:
      - ./:/home/box/web/:ro
      - ./etc/nginx.conf:/etc/nginx/sites-enabled/test.conf:ro
      - ./etc/nginx.conf:/etc/nginx/test.conf:ro
    ports:
      - "9082:80"
    network_mode: "bridge"
    # command: ["nginx"]
    # restart: always
    # domainname: foo.com
    # hostname: nginx-host
    mac_address: 02:42:ac:11:65:45
    # command: bash -c "/home/box/web/init.sh && nginx"